[package]
name = "info"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = { version = "1.45.1", features = ["full"] }
env_logger = "0.11.8"
bladerf-globals= { path= "../../crates/bladerf-globals" }
libbladerf-rs= { path= "../.." }
log = "0.4.27"