[package]
name = "libbladerf-rs"
version = "0.1.0"
edition = "2024"
authors = ["Ratzrattillo <11601995+ratzrattillo@users.noreply.github.com>"]
repository = "https://github.com/ratzrattillo/seify-bladerf"
readme = "README.md"
documentation = "https://docs.rs/seify-bladerf/"
description = "Fully Rust native BladeRF driver, powered by nusb"
license = "MIT"
keywords = ["sdr", "rf", "bladerf"]
categories = ["api-bindings"]

[workspace]
members = [".", "crates/bladerf-globals", "crates/bladerf-nios"]

[dependencies]
anyhow = "1.0"
env_logger = "0.11"
thiserror = "2.0"
nusb = { git = "https://github.com/kevinmehall/nusb", branch="main" }
tokio = { version = "1", features = ["full"]} # Only required for examples. Maybe put this in example only
bladerf-nios= { path= "crates/bladerf-nios" }
bladerf-globals= { path= "crates/bladerf-globals" }
