[package]
name = "libbladerf-rs"
version = "0.1.0"
edition = "2024"
authors = ["Ratzrattillo <11601995+ratzrattillo@users.noreply.github.com>"]
repository = "https://github.com/ratzrattillo/seify-bladerf"
readme = "README.md"
documentation = "https://docs.rs/seify-bladerf/"
description = "Fully Rust native BladeRF driver, powered by nusb"
license = "MIT"
keywords = ["sdr", "rf", "bladerf"]
categories = ["api-bindings"]

[workspace]
members = [".", "examples/info"]

[dependencies]
thiserror = "2.0"
nusb = "0.2"
log = "0.4"
num-complex = "0.4"

[dev-dependencies]
env_logger = "0.11"
