# https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=format_code_in_doc_comments#format_code_in_doc_comments
# rustup toolchain install nightly
# rustup default nightly
# rustup run nightly -- cargo fmt
format_code_in_doc_comments=true