[package]
name = "bladerf-nios"
version = "0.1.0"
edition = "2024"

[dependencies]
bladerf-globals = { path="../bladerf-globals" }
# thiserror = { version = "2.0" }

[dev-dependencies]

[[example]]
name = "packet"

[[example]]
name = "packet_retune"

[[example]]
name = "packet_retune2"